#!/bin/bash
#		to use with mpich2
#PBS -l walltime=2:00:00
#PBS -m bea
#PBS -V
#

EXEC="mpi"

if [ ! "$NFIRST" ]; then NFIRST="40"; fi;
if [ ! "$NLAST"  ]; then NLAST="200"; fi;
if [ ! "$NSTEP"  ]; then NSTEP="4";   fi;

if [ ! "$TFIRST" ]; then TFIRST="1"; fi;
if [ ! "$TLAST"  ]; then TLAST="1"; fi;
if [ ! "$TSTEP"  ]; then TSTEP="1"; fi;

if [ ! "$RUNS" ]; then RUNS="1"; fi;

cd "$PBS_O_WORKDIR";
NODES=`cat "$PBS_NODEFILE" | uniq | wc -l`;
PROCESSES=`cat "$PBS_NODEFILE" | wc -l`;
PROCESSES=1;

sort "$PBS_NODEFILE" | uniq > "mpd.hosts";
mpdboot --totalnum="$NODES" -f "$PBS_NODEFILE" --file="mpd.hosts";


T="$TFIRST";
while [ "$T" -le "$TLAST" ];
do
	echo "$T";
	N="$NFIRST";
	while [ "$N" -le "$NLAST" ];
	do
		R="1";
		RESULTS="$N";
		while [ "$R" -le "$RUNS" ];
		do
			echo -n "(${N},${T})..." 1>&2;
			RESTMP=`mpiexec -n "$PROCESSES" "$EXEC" "$N"`;
			RESULTS="${RESULTS};${RESTMP}";
			echo "DONE" 1>&2;
			R=$(( $R + 1 ));
		done;
		echo "$RESULTS";
		unset RESULTS;
		N=$(( $N + $NSTEP ));
	done;
	echo;
	T=$(( $T + $TSTEP ));
done;
