#!/bin/bash

PROCESSES="$1";
EXEC="$2";
if [ "$5" ]; then NSTART="$3"; else NSTART=40; fi;
if [ "$4" ]; then NSTOP="$4"; else NSTOP=200; fi;
if [ "$5" ]; then NSTEP="$5"; else NSTEP=4; fi;
if [ "$6" ]; then TSTART="$6"; else TSTART=1; fi;
if [ "$7" ]; then TSTOP="$7"; else TSTOP=1; fi;
if [ "$8" ]; then TSTEP="$8"; else TSTEP=1; fi;
if [ "$9" ]; then RUNS="$9"; else RUNS=1; fi;

OUTFILE="mpi-${PROCESSES}.csv";
if [ -f "$OUTFILE" ];
then
	rm "$OUTFILE";
fi;
touch "$OUTFILE";
	
T="$TSTART";
while [ "$T" -le "$TSTOP" ];
do
	echo "$T" >> "$OUTFILE";
	N="$NSTART";
	while [ "$N" -le "$NSTOP" ];
	do
		R="1";
		RESULTS="$N";
		while [ "$R" -le "$RUNS" ];
		do
			echo -n "(${N},${T})..." 1>&2;
			RESTMP=`mpiexec -np "$PROCESSES" $EXEC "$N" "$T"`;
			RESULTS="${RESULTS};${RESTMP}";
			echo "DONE" 1>&2;
			R=$(( $R + 1 ));
		done;
		echo "$RESULTS" >> "$OUTFILE";
		unset RESULTS;
		N=$(( $N + $NSTEP ));
	done;
	echo >> "$OUTFILE";
	T=$(( $T + $TSTEP ));
done;
