#!/bin/bash
#		to use with mpich2
#PBS -l walltime=2:00:00
#PBS -m bea
#
source "/etc/profile.d/env-modules.sh";
module purge;
module load gnu/mpich2-eth;

EXEC="./mpi"

if [ ! "$NFIRST" ]; then NFIRST="40"; fi;
if [ ! "$NLAST"  ]; then NLAST="200"; fi;
if [ ! "$NSTEP"  ]; then NSTEP="4";   fi;

if [ ! "$TFIRST" ]; then TFIRST="1"; fi;
if [ ! "$TLAST"  ]; then TLAST="1"; fi;
if [ ! "$TSTEP"  ]; then TSTEP="1"; fi;

if [ ! "$RUNS" ]; then RUNS="1"; fi;

cd "$PBS_O_WORKDIR";

NODES=`sort "$PBS_NODEFILE" | uniq | tee "mpd.hosts" | wc -l`;
PROCESSES=`cat "$PBS_NODEFILE" | wc -l`;

mpdboot -n "$NODES" -f "mpd.hosts";

R="1";
while [ "$R" -le "$RUNS" ];
do
	T="$TFIRST";
	while [ "$T" -le "$TLAST" ];
	do
		echo "$T";
		N="$NFIRST";
		while [ "$N" -le "$NLAST" ];
		do
			echo -n "(${N},${T})..." 1>&2;
			echo -n "$N;";
			mpiexec -n "$PROCESSES" "$EXEC" "$N" "$T";
			echo "DONE" 1>&2;
			N=$(( $N + $NSTEP ));
		done;
		T=$(( $T + $TSTEP ));
	done;
	echo;
	R=$(( $R + 1 ));
done;
