#!/bin/bash

EXEC="$1";
if [ "$2" ]; then NSTART="$2"; else NSTART=40; fi;
if [ "$3" ]; then NSTOP="$3"; else NSTOP=200; fi;
if [ "$4" ]; then NSTEP="$4"; else NSTEP=4; fi;
if [ "$5" ]; then TSTART="$5"; else TSTART=1; fi;
if [ "$6" ]; then TSTOP="$6"; else TSTOP=1; fi;
if [ "$7" ]; then TSTEP="$7"; else TSTEP=1; fi;
if [ "$8" ]; then RUNS="$8"; else RUNS=1; fi;

OUTFILE="seq.csv";
if [ -f "$OUTFILE" ];
then
	rm "$OUTFILE";
fi;
touch "$OUTFILE";
	

T="$TSTART";
while [ "$T" -le "$TSTOP" ];
do
	echo "$T" >> "$OUTFILE";
	N="$NSTART";
	while [ "$N" -le "$NSTOP" ];
	do
		R="1";
		RESULTS="$N";
		while [ "$R" -le "$RUNS" ];
		do
			echo -n "(${N},${T})..." 1>&2;
			RESTMP=`$EXEC "$N" "$T"`;
			RESULTS="${RESULTS};${RESTMP}";
			echo "DONE" 1>&2;
			R=$(( $R + 1 ));
		done;
		echo "$RESULTS" >> "$OUTFILE";
		unset RESULTS;
		N=$(( $N + $NSTEP ));
	done;
	echo >> "$OUTFILE";
	T=$(( $T + $TSTEP ));
done;
